# Generated by Django 4.1.7 on 2023-03-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('rooms', '0002_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
            preserve_default=False,
        ),
    ]
