# Generated by Django 4.1.7 on 2023-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_room_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.AddField(
            model_name="room",
            name="difficulty",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="duration_of_time",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="genre",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
