# Generated by Django 4.1.7 on 2023-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_remove_room_description_room_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="duration_of_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="genre",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
