# Generated by Django 4.1.7 on 2023-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0008_alter_room_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
