# Generated by Django 4.1.7 on 2023-04-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0009_alter_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
