# Generated by Django 4.1.7 on 2023-04-24 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0011_room_activity_room_fear_degree_alter_room_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="location",
        ),
    ]
