# Generated by Django 4.1.7 on 2023-04-30 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0013_remove_room_brand_room_branch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="duration_of_time",
            new_name="time_duration",
        ),
        migrations.RemoveField(
            model_name="room",
            name="price",
        ),
    ]
