# Generated by Django 4.1.7 on 2023-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0014_rename_duration_of_time_room_time_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="difficulty",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "🔑"), (2, "🔑🔑"), (3, "🔑🔑🔑"), (4, "🔑🔑🔑🔑"), (5, "🔑🔑🔑🔑🔑")],
                null=True,
            ),
        ),
    ]
