# Generated by Django 4.1.7 on 2023-04-30 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0015_alter_room_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="image",
            new_name="image_url",
        ),
    ]
