# Generated by Django 4.1.7 on 2023-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0016_rename_image_room_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="recommended_numb",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
