# Generated by Django 4.1.7 on 2023-04-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0017_room_recommended_numb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="activity",
            field=models.TextField(
                blank=True,
                choices=[("낮음", "🔑"), ("중간", "🔑🔑"), ("높음", "🔑🔑🔑")],
                null=True,
            ),
        ),
    ]
