# Generated by Django 4.1.7 on 2023-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0018_alter_room_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="genre",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
