# Generated by Django 4.1.7 on 2023-04-22 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "Branches"},
        ),
    ]
