# Generated by Django 4.1.7 on 2023-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0002_alter_branch_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="location",
            new_name="address",
        ),
        migrations.AddField(
            model_name="branch",
            name="city",
            field=models.CharField(default="서울특별시", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="district",
            field=models.CharField(default="서초구", max_length=100),
            preserve_default=False,
        ),
    ]
