# Generated by Django 4.1.7 on 2023-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0003_rename_location_branch_address_branch_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="booking_link",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="branch",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="branch",
            name="district",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
