# Generated by Django 4.1.7 on 2023-04-23 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0011_room_activity_room_fear_degree_alter_room_difficulty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "⭐️"),
                            (2, "⭐️⭐️"),
                            (3, "⭐️⭐️⭐️"),
                            (4, "⭐️⭐️⭐️⭐️"),
                            (5, "⭐️⭐️⭐️⭐️⭐️"),
                        ]
                    ),
                ),
                (
                    "interior_score",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "⭐️"),
                            (2, "⭐️⭐️"),
                            (3, "⭐️⭐️⭐️"),
                            (4, "⭐️⭐️⭐️⭐️"),
                            (5, "⭐️⭐️⭐️⭐️⭐️"),
                        ]
                    ),
                ),
                (
                    "story_score",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "⭐️"),
                            (2, "⭐️⭐️"),
                            (3, "⭐️⭐️⭐️"),
                            (4, "⭐️⭐️⭐️⭐️"),
                            (5, "⭐️⭐️⭐️⭐️⭐️"),
                        ]
                    ),
                ),
                (
                    "creativity_score",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "⭐️"),
                            (2, "⭐️⭐️"),
                            (3, "⭐️⭐️⭐️"),
                            (4, "⭐️⭐️⭐️⭐️"),
                            (5, "⭐️⭐️⭐️⭐️⭐️"),
                        ]
                    ),
                ),
                (
                    "problem_score",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "⭐️"),
                            (2, "⭐️⭐️"),
                            (3, "⭐️⭐️⭐️"),
                            (4, "⭐️⭐️⭐️⭐️"),
                            (5, "⭐️⭐️⭐️⭐️⭐️"),
                        ]
                    ),
                ),
                (
                    "equipment_score",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "⭐️"),
                            (2, "⭐️⭐️"),
                            (3, "⭐️⭐️⭐️"),
                            (4, "⭐️⭐️⭐️⭐️"),
                            (5, "⭐️⭐️⭐️⭐️⭐️"),
                        ]
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "room"), name="my_unique_constraint"
            ),
        ),
    ]
