# Generated by Django 4.1.7 on 2023-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="creativity_score",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="equipment_score",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="interior_score",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="problem_score",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="story_score",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
    ]
