# Generated by Django 4.1.7 on 2023-04-03 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_review_my_unique_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="my_unique_constraint",
        ),
    ]
