# Generated by Django 4.1.7 on 2023-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_remove_review_my_unique_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "room"), name="my_unique_constraint"
            ),
        ),
    ]
